### ISSUE TITLE
🐞BUG:  Hot reload & Docker optimization

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan#1036]
### Description

Currently we have our "start our frontend" with docker feature which can be done using
```shell
npm run docker-frontend
```

But there's a problem. It takes alot of time to get it started (i'm assuming maybe because of improper caching) and also if we would change up something in our file, the changes won't be reflected in the browser when we are running the frontend with docker. Here's what that needs to be done.

- Optimize the overall docker part
- Make sure the changes are always synced.
- Write a small summary of how the docker stuff works so that in future we can enhance it if needed.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by YuvarajSingh-0** [comment]
Hey, I think docker volume mounting can help reduce reloading time for every change in code. 

But as far as build speed is concerned, I think caching methods would help us out. I'm currently looking into it.

I would love to work on this issue but takes a little bit of time than what you would expect. But as this issue is open for almost a fortnight, taking time to solve this issue would do any bad.

**Comment by YuvarajSingh-0** [comment]
Can you please elaborate on 'takes alot of time to get it started'? I mean does it take much time for first start or for everytime the container is started?
