### ISSUE TITLE
[BUG] No Password validation rules

### ISSUE THREAD

**Issue by pamechayash** [MilanCommunity/Milan#1043]
### Description

in signing up as a user and as a club, in both forms there is no validation for passwords, the weakest passwords like 11111111 , 12345678 get accepted by it.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
## 📚 Info

> [!NOTE]
> Branch to make a PR/Fork would be the `beta`
> #1040 might cause small conflicts.


Hi there, you can start working on the issue. Assigning it to you.  Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans. Since we are focusing on updating Password validation, do update the regex to handle more things.

- A digit
- A Lowercase character
- An Uppercase character
- And finally a special character.

That way the strength shall increase.


## 📑 Checklist 


- **[Setup Guide](https://github.com/MilanCommunity/Milan/blob/main/README.md#-setting-up-the-project)** to understand the setup and the `.env`(s) for development locally.
- **[Contribution Guide](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#contributing-guidelines)** to understand what type of PRs are accepted and how to make them.
- **[Workflow Guide](https://github.com/MilanCommunity/Milan/blob/main/docs/Workflow.md)** to understand what goes behind the scene, and why your PR doesn't get merged immediately. <br/> <br/>

**Do drop a star, Happy Opensource 💚**
