### ISSUE TITLE
🐞Bug:  Change in position of navbar elements

### ISSUE THREAD

**Issue by dhananjay-Byte** [MilanCommunity/Milan#1089]
### Description

In the navbar when you hover over the signup button you will observer a slight positioning change in the navbar links like home , clubs and other elements. This is affecting the UI experience. Also we instead of adding a border when we hover over the solid color background button we can change the opacity of the color to highlight the active state.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi can you please show me a demo of what you mean ?

**Comment by dhananjay-Byte** [comment]
here is the demo:

![demo-gif](https://github.com/MilanCommunity/Milan/assets/82323909/9ff8033e-bcc3-41f1-9512-0fbacd9f02e0)

**Comment by tamalCodes** [comment]
Intresting, even though the UI was updated. Can you perhaps visit the `applications` tab > `cache storage` > clear all the cache ?

There seems to be a problem where the old site is delivered even when the contents were updated.

**Comment by dhananjay-Byte** [comment]
Even after clearing cache issue is not resolving @tamalCodes

**Comment by tamalCodes** [comment]
I see, I checked, and looks like this is happening (especially on my screen) when the zoom-in is `100%` or more. The issue is where the border is being affected on `hover` . You can start working on the project.

The CSS property of 
```css
border: #e26959 solid 2px;
```

 can be changed to the following to fix this issue.

```css
border: #e26959 solid 1px;
```


## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by nikhilgarg26** [comment]
i have solved the issue can i make the PR @tamalCodes

**Comment by tamalCodes** [comment]
> i have solved the issue can i make the PR @tamalCodes

Hi there the assignee has checked on the 
`I am willing to work on this issue (blank for no).` checkbox, so please do not raise PRs for the same.
