### ISSUE TITLE
[FEATURE] API for add to cart functionality

### ISSUE THREAD

**Issue by PatilHarshh** [MilanCommunity/Milan#708]
### Description

when we click to item purchase not showing adding option along with need to form items added in the navbar.

### Screenshots

![Screenshot (56)](https://github.com/IAmTamal/Milan/assets/120102234/33dc867e-2e1f-47d3-ac81-74e8a75cafcb)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find a similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @PatilHarshh , you can start to work on this !

**Comment by tamalCodes** [comment]
Hi @PatilHarshh I need some clarifications on the issue too, let's just make sure we are on the same page.

 - currently, the product has no detailed page, so there is no proper `add to cart` button. It is currently added in #701 , so we would need to get the `add to cart` button there ONCE IT IS COMPLETED.
 - So I was wondering if you could explain me in details what are the changes you are making so that we know that there wont be any conflicts !

**Comment by tamalCodes** [comment]
Interesting, so I think it will be better to go step by step. For example, we have no current way of tracking the cart, there's no proper schema, or API defined for it in the backend. 

So here's how you can proceed 

 - let us first make sure there's an API to fetch a single product, which is currently being worked on in #804 
 - Then when we have an API we can make our API add single / multiple product to the cart
 - Then we can have proper FE for the same.


So what I suggest is to wait for a while !
Once that issue is done/API is ready, you can start working on this.


How does this sounds ?

**Comment by PatilHarshh** [comment]
Sure no problem...

**Comment by tamalCodes** [comment]
Cool.

**Comment by tamalCodes** [comment]
Hi @PatilHarshh , #804 has been completed, we now have an API to fetch a single product, you can now start with making an API that has the ability to add any product to the cart. 

- Make sure we have a proper cart schema!
- We also need to make sure that the items in the cart are removable, or that more items can be added to the cart
- We also need to make sure that the cart persists, and you cannot add to the cart if you are not logged in.
- The cart is unique for every user so make sure it is done with care.

Assigning this to you.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by PatilHarshh** [comment]
@tamalCodes ok 
looking...

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this. Please reply shortly.

**Comment by PatilHarshh** [comment]
@Sa91001 I need little guidance

**Comment by PatilHarshh** [comment]
hey @tamalCodes how you want to add the cart on click on cart button passing user id and product id with request this need to change the user Schema for that . Or Alternative of this will be to work on frontent react tools only

**Comment by tamalCodes** [comment]
Hi @PatilHarshh , this issue is related to making an API for adding a product to a cart. For example, in our schema, we can add a new array to the User's schema where we have an array. 

So whenever the user calls the add-to-cart API, we push the product itself in that API which in turn get's added to that array. Check [this](https://github.com/tamalCodes/ShopCoders/blob/main/models/UserSchema.js) schema.

**Comment by PatilHarshh** [comment]
hey @tamalCodes  !! I tried to messege you on discord but you didn't replied ...
please have look on api
![Screenshot (108)](https://github.com/tamalCodes/Milan/assets/120102234/873713f3-1250-4a50-955c-a595b6a09441)

**Comment by tamalCodes** [comment]
Please can you raise a PR ? and make sure to add a screen-record to it ? 
That way it would be easier for me to see.

**Comment by PatilHarshh** [comment]
@tamalCodes still confused about this issue, you are asking recording of what ?? my issue was to make api which is mentioned in the above picture !! please provide me some reference and simplify the problem, I am early want to learn this issue now !!.

**Comment by PatilHarshh** [comment]
ok

**Comment by PatilHarshh** [comment]
https://www.loom.com/share/91155c3b3e3945d396f01f868b42502b
