### ISSUE TITLE
[FEATURE] Request to Implement Hover Effects and Animations on Cards in Event and Shop Pages

### ISSUE THREAD

**Issue by AkanshaMundel** [MilanCommunity/Milan#752]
### Description

I would like to propose the addition of hover effects and animations on all cards displayed on the event and shop pages. By incorporating these dynamic visual elements, we can make the user experience more engaging and visually appealing. When users hover over the cards, they will be greeted with interactive animations that capture their attention and provide a delightful browsing experience.

I am excited to contribute to this feature implementation and kindly request permission to proceed with adding hover effects and animations to the cards. Thank you.
I am eager to contribute to this issue and would appreciate being assigned this task under GSSOC'23.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Someone else also raised the same kind of issue 4 days ago #714  - please always check for duplicates before you proceed to make an issue. 

Anyways I will temporarily lock this, as I am waiting for them to reply, if they don't in the next few days we can proceed. Thanks.

**Comment by tamalCodes** [comment]
Hi @AkanshaMundel , you can start to work on this - as #714 was closed because of inactivity. Make sure to raise a PR once done.

### Good PR makes a Good Developer !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).**

Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.
