### ISSUE TITLE
[FEATURE] Addition of an About Us page

### ISSUE THREAD

**Issue by avoxaya** [MilanCommunity/Milan#879]
### Description

About us page can further explain the cause and motive of the web page and also It shows a more direct and professional approach from the business point of view. Please assign me this issue under GSSoC'23

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @avoxaya , we previously did have an about us page, but we removed it before long. The reason is on the Home page , it is pretty clear as to what we do, and why we do - so having a dedicated page for the same might not be useful at all.

Thanks for raising this issue, will have to close this one.
