### ISSUE TITLE
[FEATURE] Clubs detailed page.

### ISSUE THREAD

**Issue by karthiknadar1204** [MilanCommunity/Milan#924]
### Description

ON OPENING THE CLUB CARDS, THE DATA is displayed on a plain background, I felt it makes the user experience go down, like in the image below
I propose to put the contents of the page in div container with appropriate colour and border radius and some attractive animations  and place them in a manner to make the user experience better .

I also propose to dd a footer to the page as the lower part of the page looks way too blank, excessive blank spaces reduce the beauty of the page.

Also add a back button, I noticed that after opening the individual cards and accessing the clubs info, in order to navigate back to the club page, we could add a small back button with react icons to the top left corner of the page to navigate back to the original club page.

Please feel free to suggest any other changes you wish to apply to the section.
<img width="1787" alt="Screenshot 2023-07-07 at 5 11 17 PM" src="https://github.com/tamalCodes/Milan/assets/95973644/f63cbdbc-70ed-4813-a093-06fb16b37e47">

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
Hey @tamalCodes your opinion on this issue

**Comment by tamalCodes** [comment]
Hi @karthiknadar1204 , a new UI needs to be setup for the same, we have removed the exisiting page as it had a very bad UI and was not working with the legacy code we had. Now that we have refactored alot , we need a singe clubs page. What do you think ?

Currenlty we have a `Read more` button on clicking those a new page is supposed to Open-up , and inside of that page we can put up our changes. We are still working on the UI, would you like to contribute from the scratch ? 

![image](https://github.com/tamalCodes/Milan/assets/72851613/1c12a1e0-df7c-4e13-a96f-3818d5a59fd3)

If yes, please do make a new branch from `beta` and make your changes to the `beta` branch, we will put this up in https://github.com/tamalCodes/Milan/labels/Beta%20Release so that we can roll this out once all the changes are done.

**Comment by karthiknadar1204** [comment]
I would love to contribute, will create the branch soon and get working once the design is ready @tamalCodes

**Comment by tamalCodes** [comment]
Sounds good, here's the [Figma mockup](https://www.figma.com/file/HxbVrK6naTaQqUjJXCfGzU/Untitled?type=design&node-id=0%3A1&mode=design&t=bJaeQKeP9kkdw3hp-1) that i made roughly, the font's size that we are gonna have in here are gonna be pretty much similar.

The left side's orange box can be an image of the club (as per the clubs's data), and the right side has Name, TagLine and Description. We also do have a Goback button (we have a component for this already, please re-use) and a Location button too (re-use button component).

Do let me know of any questions you have. 
<br/>

### 🦄 Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.
