### ISSUE TITLE
[FEATURE] Add Required Validation on Signup form

### ISSUE THREAD

**Issue by Geeta259** [MilanCommunity/Milan#934]
### Description

Add empty validation on signup form
Validation add for valid email
Error message shown below of fields
check password & confirm password match

Currently no error show even passwords not match
![Screenshot (634)](https://github.com/tamalCodes/Milan/assets/75520947/9ba9827b-31b9-47b1-a1ba-c2d9c8de3f47)

@tamalCodes I would like to contribute on this project under GSSOC'23!!

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Teea-dev** [comment]
Hi @tamalCodes  can you please assign me to this issue so I can work on it

**Comment by tamalCodes** [comment]
Hi @Geeta259 , i think all the other checks are implemented. Try signing up with incorrect details / empty details, you will get proper error. However we are not showing the errors before someone clicks the button because we are focusing on a minimal and clean look.

![image](https://github.com/tamalCodes/Milan/assets/72851613/78366055-57c8-4699-a5d1-414399b4be4e)


However you can add checks for the `password` and the `confirm password` inside of our custom hook, and return the errors accordingly.

### Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.
