### ISSUE TITLE
[FEATURE] Hover animation on Shop Cards

### ISSUE THREAD

**Issue by parasss19** [MilanCommunity/Milan#984]
### Description

- Shop page items have no hover effects
- And its not looking attractive right now 
- I will add hover effect on shop cards

### Screenshots

https://github.com/Opentek-Org/opentek/assets/101205226/c4727de5-5afb-4a86-ad74-aba1cbc66bc9

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by parasss19** [comment]
Hey @tamalCodes Please review it once

**Comment by parasss19** [comment]
Hey @tamalCodes Please assign me this issue

**Comment by tamalCodes** [comment]
Hi there, we  will be closing all the issues that are related to shop because as you can check at: https://milanhub.org/shop, we have removed it entirely.

We will be doing stuffs in order, APIs > Design the FE > Start working on FE > Beta releases. That's the  reason why we had to remove our test shop.
